#!/bin/sh
#
# $OpenBSD: puppetmaster.rc,v 1.1 2015/04/04 09:28:45 jasper Exp $

daemon="/usr/local/bin/puppet master"

. /etc/rc.d/rc.subr

pexp="/usr/local/bin/ruby23 ${daemon}${daemon_flags:+ ${daemon_flags}}"
rc_reload=NO

rc_cmd $1
