#!/bin/sh
#
# $OpenBSD: puppet.rc,v 1.2 2015/07/15 14:49:02 ajacoutot Exp $

daemon="/usr/local/bin/puppet agent"

. /etc/rc.d/rc.subr

pexp="/usr/local/bin/ruby23 ${daemon}${daemon_flags:+ ${daemon_flags}}"
rc_reload=NO

rc_cmd $1
